version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=docker_password
      - POSTGRES_DB=art_vostorg_store

  redis:
    image: redis:latest

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: make start-in-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://docker_user:docker_password@db:5432/art_vostorg_store
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.dev

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
