# Generated by Django 3.2.18 on 2023-04-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20230429_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='painter',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='num_in_stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Number in stock'),
        ),
    ]
