# Generated by Django 3.2.18 on 2023-04-29 12:46

import authors.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=16, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('about_yourself', models.TextField(verbose_name='О себе')),
                ('avatar', sorl.thumbnail.fields.ImageField(upload_to=authors.models.get_directory_path_for_avatar, verbose_name='Аватар')),
                ('education', models.CharField(max_length=160, verbose_name='Образование')),
                ('exhibitions', models.ManyToManyField(to='authors.Exhibition', verbose_name='Выставки')),
                ('tags', models.ManyToManyField(to='authors.Tag', verbose_name='Теги')),
            ],
        ),
    ]
