# Generated by Django 3.2.18 on 2023-04-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='exhibitions',
            field=models.ManyToManyField(blank=True, to='authors.Exhibition', verbose_name='Выставки'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='tags',
            field=models.ManyToManyField(blank=True, to='authors.Tag', verbose_name='Теги'),
        ),
    ]
